
const quizEasyDB = [
  { q: "Io ___ di New York, e tu?", o: ["sono", "vengo", "sto"], a: 0, rule: "Essere vs Venire", ex: "Io sono di Roma, io vengo da Milano.", dan: "With the preposition 'di' (from), you must use the verb 'Essere' (Io sono di Roma). If you want to use 'Venire' (to come), you must use 'da' (Io vengo da Roma)." },
  { q: "Come ___ chiami?", o: ["tu", "te", "ti"], a: 2, rule: "Reflexive Pronouns", ex: "Io mi chiamo, Tu ti chiami.", dan: "In Italian, we say 'How do you call yourself?'. The reflexive pronoun for 'tu' is 'ti'. So, 'Come ti chiami?'" },
  { q: "___ cane di Marco è molto grande.", o: ["Il", "Lo", "La"], a: 0, rule: "Definite Articles", ex: "Il gatto, Lo zaino, La casa.", dan: "Correct! 'Cane' is masculine singular and starts with a normal consonant (c), so we use 'Il'." },
  { q: "Oggi io e Maria ___ al cinema.", o: ["andiamo", "vanno", "andate"], a: 0, rule: "Noi form (We)", ex: "Io e lei = Noi (We). Noi mangiamo una pizza.", dan: "'Io e Maria' equals 'Noi' (We). The present tense of 'andare' for noi is 'andiamo'." },
  { q: "Vado a dormire perché ho molto ___.", o: ["sonno", "stanchezza", "dormire"], a: 0, rule: "Avere sonno (To be sleepy)", ex: "Ho sonno, vado a letto.", dan: "In Italian, you don't say 'I am sleepy', you say 'I have sleep' (Ho sonno). It's another one of those tricky 'avere' expressions!" },
  { q: "Mi piace molto ___ pizza.", o: ["il", "la", "una"], a: 1, rule: "Articles with Piacere", ex: "Mi piace la pasta. Mi piacciono i cani.", dan: "After 'Mi piace', we almost always use the definite article because we are talking about the category in general. 'Pizza' is feminine, so 'la pizza'." },
  { q: "Io non ___ parlare bene l'italiano.", o: ["so", "conosco", "posso"], a: 0, rule: "Sapere vs Conoscere", ex: "So suonare il piano. Conosco Marco.", dan: "When talking about a skill or knowing HOW to do something (like speaking a language), we use 'Sapere' (Io so). 'Conoscere' is used for people or places." },
  { q: "Vado in Italia ___ imparare la lingua.", o: ["per", "a", "di"], a: 0, rule: "Prepositions of Purpose", ex: "Studio per imparare. Corro per dimagrire.", dan: "To express the purpose of an action (in order to...), we use the preposition 'per' followed by the infinitive verb." },
  { q: "La mia macchina è ___.", o: ["rossa", "rosso", "rossi"], a: 0, rule: "Adjective Agreement", ex: "Il libro rosso, la sedia rossa.", dan: "Adjectives must match the noun in gender and number. 'Macchina' is feminine singular, so 'rosso' becomes 'rossa'." },
  { q: "Quanti anni ___?", o: ["hai", "sei", "stai"], a: 0, rule: "Age in Italian", ex: "Ho vent'anni.", dan: "In Italian, we don't *are* our age, we *have* our years. So we ask 'Quanti anni hai?' (How many years do you have?)." }
];

const quizMediumDB = [
  { q: "Mentre mangiavo, ___ il telefono.", o: ["suonava", "ha squillato", "squilla"], a: 1, rule: "Imperfetto vs Passato Prossimo", ex: "Leggevo quando è andata via la luce.", dan: "Spot on! Use the Imperfetto ('mangiavo') for the continuous background action, and the Passato Prossimo ('ha squillato') for the sudden action that interrupts it." },
  { q: "Ho comprato un regalo per Giulia e ___ ho dato.", o: ["le", "lo", "gli"], a: 0, rule: "Indirect Pronouns", ex: "Le parlo (I speak to her). Gli parlo (I speak to him).", dan: "Here you are giving a gift TO her. The indirect object pronoun for 'a lei' (to her) is 'le'." },
  { q: "Non credo che Luigi ___ ragione.", o: ["ha", "abbia", "avesse"], a: 1, rule: "Il Congiuntivo (Subjunctive)", ex: "Penso che sia vero. Spero che tu venga.", dan: "Verbs expressing opinion or doubt like 'Credere', 'Pensare', or 'Sperare' trigger the Subjunctive mood. The present subjunctive of 'avere' is 'abbia'." },
  { q: "Ieri sera ___ a casa a mezzanotte.", o: ["sono tornato", "ho tornato", "tornavo"], a: 0, rule: "Passato Prossimo with Essere", ex: "Sono andato al supermercato. È partita.", dan: "'Tornare' is a verb of movement/return, so it requires 'Essere' as the auxiliary. Don't forget to match the ending (tornato/a) to the subject!" },
  { q: "Hai visto il mio libro? Non ___ trovo più.", o: ["lo", "il", "gli"], a: 0, rule: "Direct Object Pronouns", ex: "La mangio (I eat it). Li compro (I buy them).", dan: "You are looking for 'il libro' (masculine singular). The direct pronoun to replace it is 'lo' (I can't find IT)." },
  { q: "Se piove, non ___ al mare.", o: ["andrei", "andrò", "andassi"], a: 1, rule: "Periodo Ipotetico (Type 1)", ex: "Se studio, passo l'esame. Se mangio troppo, starò male.", dan: "This is a real possibility (First Conditional). If + Present tense (Se piove), then Future tense in the main clause (non andrò)." },
  { q: "Il film ___ ho visto ieri era bellissimo.", o: ["che", "chi", "quale"], a: 0, rule: "Relative Pronouns", ex: "Il libro che leggo. La ragazza che parla.", dan: "'Che' translates to 'that' or 'which' and is the most common relative pronoun used to connect two sentences. 'Chi' is only used for 'who/those who' in general statements." },
  { q: "È un segreto. Non dirlo a ___!", o: ["niente", "nessuno", "qualcuno"], a: 1, rule: "Double Negatives", ex: "Non vedo niente. Non c'è nessuno.", dan: "In Italian, double negatives are perfectly correct! 'Non dirlo a nessuno' translates to 'Don't tell it to nobody' (Don't tell anyone)." },
  { q: "Abbiamo deciso ___ partire domani.", o: ["di", "a", "per"], a: 0, rule: "Verbs with Prepositions", ex: "Ho deciso di uscire. Ho dimenticato di chiamare.", dan: "The verb 'Decidere' always requires the preposition 'di' before another infinitive verb. Decidere DI fare qualcosa." },
  { q: "Questa è la casa ___ sono nato.", o: ["in cui", "che", "dove"], a: 2, rule: "Dove vs In cui", ex: "La città in cui vivo. La scuola dove studio.", dan: "Both 'in cui' and 'dove' are grammatically correct here, but 'dove' (where) is the most natural and direct way to indicate a physical place." }
];

const quizHardDB = [
  { q: "Se io ___ studiato di più, avrei passato l'esame.", o: ["avessi", "avevo", "avrei"], a: 0, rule: "Periodo Ipotetico (Type 3)", ex: "Se avessi saputo, sarei andato.", dan: "Welcome to the Impossible Past! For things that didn't happen, use 'Se' + Congiuntivo Trapassato (Se avessi studiato), and Condizionale Passato (avrei passato)." },
  { q: "Nonostante ___ tardi, siamo usciti lo stesso.", o: ["era", "fosse", "sia"], a: 1, rule: "Congiuntivo with Concessive clauses", ex: "Nonostante piova, esco. Benché fosse stanco, lavorò.", dan: "The conjunction 'Nonostante' (Despite/Even though) ALWAYS requires the subjunctive. Since the main action is in the past ('siamo usciti'), we need the Imperfect Subjunctive ('fosse')." },
  { q: "___, non sopporto la gente che urla.", o: ["A dirla tutta", "Di dire tutto", "Per dire tutto"], a: 0, rule: "Advanced Idioms", ex: "A dirla tutta, non mi piace per niente.", dan: "'A dirla tutta' is a fantastic conversational filler that translates to 'To be completely honest' or 'Truth be told'." },
  { q: "Il ladro è ___ arrestato dalla polizia.", o: ["stato", "avuto", "venuto"], a: 0, rule: "Passive Voice", ex: "La mela è mangiata da me. L'edificio è stato costruito.", dan: "In the passive voice, we use the verb 'Essere' (or 'Venire') + the past participle. 'È stato arrestato' means 'He was arrested'." },
  { q: "Me ne ___ subito!", o: ["vado", "ando", "parto"], a: 0, rule: "Verbi Pronominali (Andarsene)", ex: "Io me ne vado. Lui se ne andò.", dan: "The verb 'Andarsene' means 'to get out of here' or 'to leave'. 'Me ne vado' translates to 'I'm getting out of here!'" },
  { q: "Appena ___ di piovere, uscimmo a fare due passi.", o: ["ha smesso", "ebbe smesso", "smetteva"], a: 1, rule: "Trapassato Remoto", ex: "Appena ebbe finito di parlare, se ne andò.", dan: "Very advanced! Used mostly in literature after time conjunctions like 'appena' (as soon as) to show an action completed right before another past action." },
  { q: "Ce ___ voluto molto tempo per convincerlo.", o: ["è", "ha", "sia"], a: 0, rule: "Volerci vs Metterci", ex: "Ci vuole un'ora. Ci metto un'ora.", dan: "We use 'Volerci' (to take time). Since 'molto tempo' is singular, it acts as the subject, so we use the singular 'ci è voluto' (often contracted to 'c'è voluto')." },
  { q: "Non sapevo che tu ___ già mangiato.", o: ["avevi", "avessi", "abbia"], a: 1, rule: "Congiuntivo Trapassato", ex: "Credevo che fosse già partito.", dan: "You didn't know (past) that they had eaten BEFORE that moment (even further in the past). So you need the past perfect subjunctive ('avessi mangiato')." },
  { q: "Sono stufo che tu ti ___ sempre dei miei problemi.", o: ["lamenti", "lamenta", "lamentassi"], a: 0, rule: "Congiuntivo with Emotions", ex: "Sono felice che tu stia bene. Temo che piova.", dan: "'Sono stufo' expresses an emotion/state of mind, which triggers the subjunctive. The 'tu' form present subjunctive of lamentarsi is 'ti lamenti'." },
  { q: "Ne abbiamo ___ a sufficienza di queste scuse.", o: ["sentito", "sentite", "sentiti"], a: 1, rule: "Participle Agreement with 'Ne'", ex: "Ho mangiato due mele -> Ne ho mangiate due.", dan: "When you use the partitive pronoun 'NE', the past participle MUST agree with the gender and number of the noun it replaces ('le scuse' = feminine plural = sentite)." }
];

const quizNativeDB = [
  { q: "Qual è il plurale di 'braccio' quando parliamo del corpo umano?", o: ["I bracci", "Le braccia", "Le braccie"], a: 1, rule: "Plurali Sovrabbondanti", ex: "Il braccio -> Le braccia. Il lenzuolo -> Le lenzuola.", dan: "Italian is crazy! Some words have two plurals. 'I bracci' means the arms of a machine/crane. 'Le braccia' (feminine plural) means human arms!" },
  { q: "Dobbiamo tagliare la corda. Significa:", o: ["Dobbiamo scappare", "Dobbiamo lavorare", "Dobbiamo rompere qualcosa"], a: 0, rule: "Idioms (Tagliare la corda)", ex: "La polizia sta arrivando, tagliamo la corda!", dan: "'Tagliare la corda' literally means 'to cut the rope'. It's an old nautical term meaning to release a boat quickly to escape. It means 'Let's get out of here quickly!'" },
  { q: "Non fare il portoghese! Significa:", o: ["Non parlare in un'altra lingua", "Non entrare senza pagare il biglietto", "Non essere avaro"], a: 1, rule: "Historical Idioms", ex: "Entrare gratis a uno spettacolo = Fare il portoghese.", dan: "In 18th-century Rome, the Portuguese embassy hosted a free event for Portuguese citizens. Romans tried to fake being Portuguese to get in for free. 'Fare il portoghese' means sneaking in without paying!" },
  { q: "Nel 1265 Dante Alighieri ___ a Firenze.", o: ["nascette", "nacque", "nasceva"], a: 1, rule: "Passato Remoto Irregolare", ex: "Io nacqui, lui nacque, loro nacquero.", dan: "Historical events usually take the Passato Remoto. The verb 'nascere' is highly irregular: io nacqui, tu nascesti, lui nacque." },
  { q: "Quel ragazzo ha molto sale in zucca. Significa:", o: ["È intelligente", "È stupido", "Ha fame"], a: 0, rule: "Idioms (Sale in zucca)", ex: "Ascolta lui, ha molto sale in zucca.", dan: "'Sale' (salt) historically represents wisdom or flavor. 'Zucca' (pumpkin) is slang for 'head'. Having salt in your pumpkin means you are a very smart person." },
  { q: "Ho comprato tre paia di ___.", o: ["lenzuoli", "lenzuole", "lenzuola"], a: 2, rule: "Irregular Feminine Plurals", ex: "L'uovo -> Le uova. Il lenzuolo -> Le lenzuola.", dan: "Just like 'braccia' or 'uova', 'lenzuolo' (bed sheet) is masculine in the singular, but becomes feminine in the plural ending in -a: 'le lenzuola'." },
  { q: "È inutile piangere sul latte ___.", o: ["versato", "caduto", "rovesciato"], a: 0, rule: "Proverbs", ex: "Hai sbagliato, ma è inutile piangere sul latte versato.", dan: "Just like in English, 'Non piangere sul latte versato' means 'Don't cry over spilt milk'." },
  { q: "___ ai ripari prima che sia troppo tardi.", o: ["Corriamo", "Andiamo", "Saltiamo"], a: 0, rule: "Collocations", ex: "Dobbiamo correre ai ripari.", dan: "'Correre ai ripari' is a set phrase that means 'to run for cover' or to fix a problem before it causes a disaster." },
  { q: "Qual è il plurale di 'Muro' se intendiamo le pareti di una casa?", o: ["I muri", "Le mura", "I muretti"], a: 1, rule: "Plurali Sovrabbondanti (Muro)", ex: "I muri (esterno), Le mura (città o casa).", dan: "'I muri' usually refers to standalone walls outside (like a garden wall). 'Le mura' refers to the walls enclosing a city or a room." },
  { q: "L'esame era un gioco da ragazzi. Significa:", o: ["Era molto difficile", "Era molto facile", "Era per bambini"], a: 1, rule: "Idioms (Gioco da ragazzi)", ex: "Questo test è un gioco da ragazzi.", dan: "'Un gioco da ragazzi' literally means 'a boys' game'. It's the Italian equivalent of 'a piece of cake'!" }
];

const traduzioniEasyDB = [
  { q: "Good morning, I would like a coffee.", a: ["buongiorno vorrei un caffè", "buon giorno vorrei un caffè"], dan: "In Italy, we always say 'Vorrei' (I would like) when ordering politely. Never say 'Voglio' (I want), it sounds very rude to the barista!" },
  { q: "Where is the train station?", a: ["dov'è la stazione dei treni", "dove è la stazione dei treni", "dov'è la stazione"], dan: "'Dov'è' is the contraction of 'Dove è'. Remember that 'stazione' is feminine, so it's 'la stazione'." },
  { q: "I am hungry and I am thirsty.", a: ["ho fame e ho sete", "ho fame ed ho sete"], dan: "Remember our golden rule! In Italian, you don't *are* hungry, you *have* hunger (avere fame) and *have* thirst (avere sete)." },
  { q: "Nice to meet you.", a: ["piacere di conoscerti", "piacere", "molto piacere", "piacere mio"], dan: "You can simply say 'Piacere' (Pleasure). It's the most common and natural way to say 'Nice to meet you' when shaking hands!" },
  { q: "I don't speak Italian very well.", a: ["non parlo molto bene l'italiano", "non parlo l'italiano molto bene", "non parlo bene l'italiano"], dan: "Place 'non' right before the verb to make it negative. And don't worry, Italians will love that you are trying!" },
  { q: "How old are you?", a: ["quanti anni hai"], dan: "Literally 'How many years do you have?'. We use the verb 'avere' (to have) for age, not 'essere' (to be)." },
  { q: "I'm sorry, I don't understand.", a: ["mi dispiace non capisco", "scusa non capisco", "scusi non capisco"], dan: "'Mi dispiace' or 'Scusa' work perfectly here. 'Non capisco' comes from the verb 'capire' (to understand)." },
  { q: "Can you repeat, please?", a: ["puoi ripetere per favore", "può ripetere per favore"], dan: "'Puoi' is informal (tu), while 'Può' is formal (Lei). Add 'per favore' (please) to be extra polite!" },
  { q: "What time is it?", a: ["che ore sono", "che ora è"], dan: "Both 'Che ore sono?' (plural) and 'Che ora è?' (singular) are perfectly fine and used interchangeably by Italians." },
  { q: "The check, please.", a: ["il conto per favore"], dan: "Crucial for restaurants! 'Il conto' is the check/bill. In Italy, you usually have to ask for it, the waiter won't rush you to leave." }
];

const traduzioniMediumDB = [
  { q: "I went to Rome two years ago.", a: ["sono andato a roma due anni fa", "sono andata a roma due anni fa"], dan: "For verbs of movement like 'andare', you must use 'essere' as the auxiliary verb. Don't forget to match the ending to your gender (-o for men, -a for women)!" },
  { q: "I have known him since I was a child.", a: ["lo conosco da quando ero bambino", "lo conosco da quando ero bambina", "lo conosco da bambino"], dan: "Tricky one! In Italian, if an action started in the past and is STILL ongoing, we use the Present tense (lo conosco) + 'da' (since/for)." },
  { q: "Did you like the movie?", a: ["ti è piaciuto il film", "vi è piaciuto il film"], dan: "The verb 'piacere' works backward. 'Il film' is the subject doing the pleasing. So it's 'Was the movie pleasing to you?' -> Ti è piaciuto?" },
  { q: "I'll call you as soon as I arrive.", a: ["ti chiamo appena arrivo", "ti chiamerò non appena arrivo", "ti chiamo non appena arrivo"], dan: "You can use the present tense for future events in Italian. 'Appena' means 'as soon as'. Notice how we put the pronoun 'ti' before the verb 'chiamo'." },
  { q: "I don't think it's a good idea.", a: ["non penso che sia una buona idea", "non credo che sia una buona idea", "non credo sia una buona idea"], dan: "Verbs expressing opinion or doubt (pensare, credere) + 'che' trigger the Subjunctive mood! So 'è' becomes 'sia'." },
  { q: "We were eating when he called.", a: ["stavamo mangiando quando ha chiamato", "mangiavamo quando ha chiamato"], dan: "You can use 'Stare + gerundio' (stavamo mangiando) or simply the Imperfetto (mangiavamo) for an ongoing past action interrupted by the Passato Prossimo (ha chiamato)." },
  { q: "I need to buy them. (referring to shoes)", a: ["le devo comprare", "devo comprarle", "ho bisogno di comprarle"], dan: "With modal verbs like 'dovere', you can put the direct pronoun 'le' (them, feminine plural) either before the conjugated verb OR attached to the end of the infinitive!" },
  { q: "It's the most beautiful city I have ever seen.", a: ["è la città più bella che io abbia mai visto", "è la città più bella che abbia mai visto"], dan: "Superlatives ('la più bella') trigger the subjunctive in the relative clause! So we use 'abbia visto' instead of 'ho visto'." },
  { q: "If I have time, I'll help you.", a: ["se ho tempo ti aiuto", "se avrò tempo ti aiuterò", "se ho tempo ti aiuterò"], dan: "First conditional! Real possibility. You can use Present + Present ('se ho... aiuto') or Future + Future." },
  { q: "I'm looking forward to the holidays.", a: ["non vedo l'ora delle vacanze", "non vedo l'ora che arrivino le vacanze"], dan: "The best Italian idiom! 'Non vedo l'ora' literally means 'I don't see the hour'. It perfectly translates 'I'm looking forward to'." }
];

const traduzioniHardDB = [
  { q: "If I had known, I wouldn't have come.", a: ["se lo avessi saputo non sarei venuto", "se l'avessi saputo non sarei venuto", "se avessi saputo non sarei venuto"], dan: "Third conditional! Impossible past. You need 'Se' + Congiuntivo Trapassato (avessi saputo) and Condizionale Passato (sarei venuto)." },
  { q: "It is necessary that the work be finished by tomorrow.", a: ["è necessario che il lavoro sia finito per domani", "è necessario che il lavoro venga finito per domani", "bisogna che il lavoro sia finito entro domani"], dan: "Impersonal expressions like 'È necessario che...' ALWAYS trigger the subjunctive. Here we also have a passive voice (sia finito / venga finito)." },
  { q: "I couldn't care less.", a: ["non me ne importa niente", "non me ne frega niente", "non me ne frega un cazzo"], dan: "'Non me ne frega niente' is very common and a bit informal. The pronominal verb 'fregarsene' takes the pronouns 'me' + 'ne'." },
  { q: "He acts as if he knew everything.", a: ["fa finta di sapere tutto", "si comporta come se sapesse tutto", "fa come se sapesse tutto"], dan: "'Come se' (as if) introduces an unreal situation in the present, so it strictly requires the Congiuntivo Imperfetto (sapesse)." },
  { q: "It took me two hours to get here.", a: ["ci ho messo due ore per arrivare qui", "mi ci sono volute due ore per arrivare qui"], dan: "The verb 'metterci' refers to the time a *person* spends doing something. 'Volerci' refers to the time *needed* generally. 'Ci ho messo' = I put two hours into it." },
  { q: "The book you told me about is very interesting.", a: ["il libro di cui mi hai parlato è molto interessante", "il libro del quale mi hai parlato è molto interessante"], dan: "When a relative pronoun is the object of a preposition (parlare DI un libro), we use 'cui' or 'il/la quale'. So, 'di cui' (of which)." },
  { q: "I would rather you didn't say anything.", a: ["preferirei che tu non dicessi niente", "preferirei che non dicessi nulla"], dan: "'Preferirei' (I would prefer) expresses a wish about someone else's action, so the subordinate clause takes the Congiuntivo Imperfetto (dicessi)." },
  { q: "We must make do with what we have.", a: ["dobbiamo accontentarci di quello che abbiamo", "dobbiamo farci bastare quello che abbiamo", "bisogna farsi bastare quello che si ha"], dan: "'Accontentarsi' (to be satisfied with) or 'farsi bastare' (to make enough for oneself) are the perfect translations for 'making do'." },
  { q: "No matter how much it costs, I will buy it.", a: ["non importa quanto costa lo comprerò", "per quanto costi lo comprerò", "costi quel che costi lo comprerò"], dan: "'Costi quel che costi' is a fantastic idiomatic chunk (whatever it takes). If you use 'per quanto', it requires the subjunctive (costi)!" },
  { q: "By the time you arrive, I will have already left.", a: ["quando arriverai sarò già partito", "per quando arriverai sarò già partito", "quando arrivi sarò già partito"], dan: "The Future Perfect (Futuro Anteriore) is used for an action that will be completed before another future action. 'Sarò partito' (I will have left)." }
];

const traduzioniNativeDB = [
  { q: "It's raining cats and dogs.", a: ["piove a catinelle", "piove a dirotto"], dan: "We don't rain animals in Italy! We rain 'a catinelle' (buckets/basins) or 'a dirotto' (pouring). Never literally translate English idioms!" },
  { q: "To make a long story short.", a: ["per farla breve", "in poche parole"], dan: "'Per farla breve' (to make it short) is the perfect equivalent. Notice the pronoun 'la' refers to 'la storia' or 'la questione'." },
  { q: "I have a frog in my throat.", a: ["ho un rospo in gola", "ho un nodo in gola"], dan: "In Italian, it's not a frog, it's a 'rospo' (a toad)! We say 'Ho un rospo in gola'. We also use 'sputare il rospo' (spit the toad) for 'spit it out / confess'." },
  { q: "Speak of the devil!", a: ["parli del diavolo", "parli del diavolo e spuntano le corna", "lupus in fabula"], dan: "We say 'Parli del diavolo e spuntano le corna' (Speak of the devil and the horns appear). Another very cultured Latin alternative is 'Lupus in fabula' (the wolf in the tale)." },
  { q: "He is pulling my leg.", a: ["mi sta prendendo in giro", "mi prende in giro"], dan: "We don't pull legs. We 'take someone around' (prendere in giro), which means to tease or mock them." },
  { q: "It’s a piece of cake.", a: ["è un gioco da ragazzi", "è una passeggiata", "è facilissimo", "è un pezzo di torta"], dan: "Food is serious business in Italy, we don't usually use cake for 'easy'. We say 'È un gioco da ragazzi' (It's a kids' game) or 'È una passeggiata' (It's a stroll)." },
  { q: "To beat around the bush.", a: ["menare il can per l'aia", "girarci intorno", "girare intorno all'argomento"], dan: "The literal and very old idiom is 'Menare il can per l'aia' (to lead the dog around the farmyard), but 'Girarci intorno' (to walk around it) is more common today." },
  { q: "I'm feeling under the weather.", a: ["non mi sento molto bene", "mi sento un po' giù", "non sono in forma"], dan: "We don't have a weather idiom for this. 'Mi sento un po' giù' (I feel a bit down) or 'Non sono in forma' (I'm not in shape) work best." },
  { q: "Break a leg!", a: ["in bocca al lupo", "merda merda merda"], dan: "Just like the pillola you learned! We say 'In bocca al lupo' (Into the wolf's mouth). In theater, Italians also say 'Merda merda merda' (very similar to the French 'merde')." },
  { q: "To kick the bucket.", a: ["tirare le cuoia", "crepare", "andare all'altro mondo"], dan: "Instead of kicking a bucket, Italians 'tirano le cuoia' (pull the leather - referring to animal skins tightening when they die). It's a very colloquial way to say 'to die'." }
];

const multisensoEasyDB = [
  { q: "Vado via, ci vediamo domani. <u style='color:var(--primary)'>Ciao</u>!", o: ["Hello", "Goodbye", "Please"], a: 1, dan: "'Ciao' is the ultimate double-agent word! It means both 'Hello' when you meet someone and 'Goodbye' when you leave. Here, since the person is leaving, it means Goodbye!" },
  { q: "Sono molto stanco, vado a <u style='color:var(--primary)'>letto</u>.", o: ["I read", "Bed", "Read (past participle)"], a: 1, dan: "Right! 'Letto' means 'Bed'. However, it is also the past participle of the verb 'Leggere' (to read). So 'Ho letto un libro a letto' means 'I read a book in bed'!" },
  { q: "Oggi c'è un bellissimo <u style='color:var(--primary)'>sole</u> nel cielo.", o: ["Sun", "Alone (fem. plural)", "Only"], a: 0, dan: "Correct! 'Il sole' is the Sun. But 'sole' is also the feminine plural of 'solo' (alone). 'Due donne sole' means 'Two women alone'." },
  { q: "Io non <u style='color:var(--primary)'>so</u> parlare il francese.", o: ["I know", "Under", "I am"], a: 0, dan: "Bravo! 'So' is the first person of 'Sapere' (I know / I know how to). Don't confuse it with 'Sotto' which means 'under'." },
  { q: "Uso la <u style='color:var(--primary)'>penna</u> blu per firmare il documento.", o: ["Feather", "Pen", "Pasta shape"], a: 1, dan: "Exactly, a writing pen. But fun fact: 'penna' historically meant 'bird feather' (which they used to write with). And yes, the pasta 'Penne' is named after the quill pen shape!" },
  { q: "Il mio appartamento è al secondo <u style='color:var(--primary)'>piano</u>.", o: ["Floor / Level", "Piano (Instrument)", "Slowly"], a: 0, dan: "Here it means 'Floor' of a building. But 'piano' also means 'Slowly/Softly' (Parla piano!) and of course, the musical instrument (Il pianoforte, often just called piano)!" },
  { q: "Vado a <u style='color:var(--primary)'>pesca</u> al lago con mio nonno.", o: ["Peach", "Fishing", "Fish"], a: 1, dan: "Context is everything! 'La pèsca' (open E) means 'a peach', but 'La pésca' (closed E) means 'fishing'. Here you go fishing at the lake, you don't go 'peach'!" },
  { q: "Domani lo <u style='color:var(--primary)'>farò</u> senza problemi.", o: ["Lighthouse", "I will do", "Pharaoh"], a: 1, dan: "It's the future tense of Fare: 'I will do it'. But 'Il faro' (without the accent on the O) means 'Lighthouse' or 'Car headlight'!" },
  { q: "Non mangiare troppo <u style='color:var(--primary)'>riso</u> a cena.", o: ["Rice", "Laughter", "Smile"], a: 0, dan: "Here it's the food 'rice'. However, 'il riso' also means 'the laughter'. An old Italian proverb says: 'Il riso abbonda sulla bocca degli stolti' (Laughter abounds in the mouths of fools)." },
  { q: "Roma è un grande <u style='color:var(--primary)'>stato</u> antico? No, una città.", o: ["Been", "State / Nation", "Status"], a: 1, dan: "Here 'stato' means State or Nation. But 'stato' is also the past participle of Essere (To be). 'Sono stato a Roma' = I have been to Rome." }
];

const multisensoMediumDB = [
  { q: "Non ho <u style='color:var(--primary)'>tempo</u> per queste sciocchezze.", o: ["Weather", "Time", "Tempo (Music)"], a: 1, dan: "Spot on! 'Tempo' means both Time and Weather in Italian. You have to use the context. 'Che brutto tempo' = What bad weather. 'Non ho tempo' = I have no time." },
  { q: "Milano è la <u style='color:var(--primary)'>capitale</u> della moda.", o: ["Capital city", "Capital (Money/Funds)", "Capital letter"], a: 0, dan: "'La capitale' (feminine) is the Capital City. 'Il capitale' (masculine) refers to money or financial funds!" },
  { q: "Qual è il <u style='color:var(--primary)'>fine</u> di questa ricerca?", o: ["The end", "The purpose / Goal", "Fine / Thin"], a: 1, dan: "Tricky! 'La fine' (feminine) is the end of something (la fine del film). 'Il fine' (masculine) is the purpose or goal of an action!" },
  { q: "Prendi i bicchieri che sono nella <u style='color:var(--primary)'>credenza</u>.", o: ["Belief / Faith", "Cupboard / Cabinet", "Credit"], a: 1, dan: "In the kitchen, a 'credenza' is a cupboard. But philosophically, 'una credenza' is a belief or superstition!" },
  { q: "Per favore, paga alla <u style='color:var(--primary)'>cassa</u>.", o: ["Crate / Box", "Speaker", "Checkout / Cash register"], a: 2, dan: "In a supermarket, 'la cassa' is the checkout. But it also means a wooden crate, or an audio speaker (cassa acustica)!" },
  { q: "Il gatto <u style='color:var(--primary)'>sale</u> sul tetto.", o: ["Salt", "He/She goes up", "Rooms (plural)"], a: 1, dan: "Watch out! 'Il sale' is the salt you put on food. But here it's the 3rd person singular of the verb 'Salire' (to go up / to climb)!" },
  { q: "Il vino buono sta nella <u style='color:var(--primary)'>botte</u> piccola.", o: ["Barrel / Cask", "Beating / Blows", "Boots"], a: 0, dan: "This is a famous proverb meaning 'good things come in small packages'. 'La botte' is a wine barrel. But 'le botte' (plural) means physical beatings/blows!" },
  { q: "Non credergli, lui <u style='color:var(--primary)'>mente</u> sempre!", o: ["Mind / Brain", "Mint (Herb)", "He/She lies"], a: 2, dan: "Here it is the verb 'Mentire' (to lie). But 'la mente' means the human mind, and 'la menta' is the mint herb." },
  { q: "Il treno per Napoli <u style='color:var(--primary)'>parte</u> alle 8:00.", o: ["Part / Portion", "He/She leaves", "Party"], a: 1, dan: "It's the verb 'Partire' (to leave / depart). 'La parte', however, means a piece or portion of something." },
  { q: "La nave ha gettato l'<u style='color:var(--primary)'>ancora</u> nel porto.", o: ["Still / Yet", "Anchor", "Again"], a: 1, dan: "Pronunciation matters! 'Ancóra' (stress on O) means 'Still/Yet/Again'. But 'Àncora' (stress on A) is a ship's Anchor!" }
];

const multisensoHardDB = [
  { q: "Quel bambino non sta mai fermo, è una vera <u style='color:var(--primary)'>peste</u>!", o: ["Plague / Disease", "Naughty child / Menace", "Pesto sauce"], a: 1, dan: "Literally 'peste' means the plague (the Black Death). But colloquially, we call a very naughty, hyperactive child 'una peste'!" },
  { q: "Guidava l'auto a una velocità <u style='color:var(--primary)'>folle</u>.", o: ["Crowds", "Crazy / Insane", "Neutral gear"], a: 1, dan: "Here it means 'Crazy' speed. But 'le folle' means 'the crowds' of people. Also, in a car, 'mettere in folle' means to put the gear in neutral!" },
  { q: "Il <u style='color:var(--primary)'>tasso</u> di disoccupazione è in calo.", o: ["Badger (Animal)", "Yew (Tree)", "Rate / Percentage"], a: 2, dan: "In economics, 'il tasso' is the rate (tasso di interesse). In biology, 'il tasso' is a badger (the animal) AND a yew tree!" },
  { q: "Mi scusi, devo firmare la <u style='color:var(--primary)'>bolla</u> di consegna.", o: ["Bubble", "Delivery note / Invoice", "He/She boils"], a: 1, dan: "In logistics, 'la bolla' is a delivery note or packing slip. Otherwise, it means a soap bubble (bolla di sapone). The verb 'bollire' (to boil) uses 'bolle', not bolla." },
  { q: "Ho pagato la bolletta in ritardo e mi hanno addebitato la <u style='color:var(--primary)'>mora</u>.", o: ["Blackberry (Fruit)", "Dark-haired woman", "Late payment fee"], a: 2, dan: "A nightmare for Italians! 'La mora' is a financial penalty/late fee. But it also means a blackberry fruit, and a woman with dark brown hair!" },
  { q: "Per favore, metti la tua <u style='color:var(--primary)'>firma</u> in fondo al contratto.", o: ["Signature", "He/She signs", "Firm / Company"], a: 0, dan: "'La firma' is your signature! Don't confuse it with 'azienda' or 'ditta' which mean Company/Firm." },
  { q: "Oggi in autostrada c'era una <u style='color:var(--primary)'>coda</u> di dieci chilometri.", o: ["Tail (Animal)", "Queue / Traffic jam", "Pigtail (Hair)"], a: 1, dan: "It literally means an animal's 'Tail', but we use it constantly to mean a line of people waiting, or a massive traffic jam!" },
  { q: "Attento a non tagliarti, la <u style='color:var(--primary)'>lama</u> è molto affilata.", o: ["Llama (Animal)", "Blade", "Mud"], a: 1, dan: "Here it is the sharp 'Blade' of a knife. The animal from South America is also called 'lama' in Italian. Mud is 'fango'." },
  { q: "Dove hai <u style='color:var(--primary)'>posto</u> le chiavi di casa?", o: ["Place / Spot", "Put / Placed (Past Participle)", "Seat"], a: 1, dan: "'Il posto' is a place or a seat. But here it acts as the past participle of the verb 'Porre' (to put/place). Where did you *put* the keys?" },
  { q: "Oggi pomeriggio <u style='color:var(--primary)'>ritiro</u> il pacco in posta.", o: ["Withdrawal", "Retreat (Sports/Military)", "I pick up / I collect"], a: 2, dan: "As a noun, 'il ritiro' is a withdrawal or sports retreat. As a verb (Ritirare), 'io ritiro' means 'I pick up' or 'I collect' something." }
];

const multisensoNativeDB = [
  { q: "Ha tirato indietro il <u style='color:var(--primary)'>cane</u> della pistola.", o: ["Dog", "Gun hammer", "Incompetent person"], a: 1, dan: "In firearms, 'il cane' is the hammer of the gun. Also, if an actor or singer is terrible, Italians say 'È un cane!' (He is a dog)." },
  { q: "Il paziente è stato operato per un <u style='color:var(--primary)'>calcolo</u> renale.", o: ["Calculation / Math", "Gallstone / Kidney stone", "Estimate"], a: 1, dan: "In math, 'un calcolo' is a calculation. In medicine, it is a stone (like a kidney stone - calcolo renale). Comes from Latin 'calculus' meaning 'small pebble'!" },
  { q: "Il giocatore ha tirato al volo e ha segnato una <u style='color:var(--primary)'>rete</u> magnifica!", o: ["Network (Internet)", "Net", "Goal (Sports)"], a: 2, dan: "Literally 'rete' means a physical Net, which extended to mean Network (like Internet). In soccer, hitting the net means scoring a 'Goal'!" },
  { q: "Mi passi il cacciavite? Manca una <u style='color:var(--primary)'>vite</u> nel mobile.", o: ["Vine (Plant)", "Lives (Plural of Vita)", "Screw"], a: 2, dan: "A 'vite' is a metal Screw. It is also the Grape Vine plant. And it's the plural of 'la vita' (the life). A true triple-threat word!" },
  { q: "Mentre l'aereo decollava, si sentiva un forte <u style='color:var(--primary)'>rombo</u>.", o: ["Rhombus (Geometry)", "Turbot (Fish)", "Rumble / Roar"], a: 2, dan: "It means a loud rumble or roar (like an engine). It also means the Rhombus geometric shape, AND the Turbot flatfish!" },
  { q: "L'avvocato è specializzato in diritto <u style='color:var(--primary)'>penale</u>.", o: ["Penalty / Fee", "Criminal", "Painful"], a: 1, dan: "In law, 'diritto penale' means Criminal Law. As a noun, 'la penale' is a financial penalty for breaking a contract." },
  { q: "Mi si è spezzata la <u style='color:var(--primary)'>mina</u> della matita.", o: ["Mine (Explosive)", "Graphite lead", "Female singer"], a: 1, dan: "'La mina' is an explosive landmine. But in a pencil, it's the tiny graphite lead inside! (Mina is also the name of Italy's most legendary singer)." },
  { q: "Hanno festeggiato 50 anni di matrimonio e lui ha perso la <u style='color:var(--primary)'>fede</u>.", o: ["Faith / Religion", "Wedding ring", "Loyalty"], a: 1, dan: "'La fede' is Faith or Religion. Because a wedding ring represents faith and loyalty, the ring itself is called 'La fede nuziale'." },
  { q: "Non studia mai, il professore lo <u style='color:var(--primary)'>boccia</u> di sicuro.", o: ["Glass bowl", "Flunks / Fails him", "Bocce ball"], a: 1, dan: "As a noun, 'una boccia' is a glass bowl or a ball for the game of Bocce. As a verb (Bocciare), it means to flunk/fail a student in school!" },
  { q: "Scalare l'Everest senza ossigeno è stata un'<u style='color:var(--primary)'>impresa</u> storica.", o: ["Company / Business", "Cleaning service", "Feat / Epic deed"], a: 2, dan: "'Un'impresa' is usually a commercial Company or Enterprise. But it also means a legendary feat, an epic undertaking or deed!" }
];

const commediaEasyDB = [
  { text: "Cosa fa un pomodoro al mattino?\nLa passata.", dan: "A 'pomodoro' is a tomato. 'La passata' is tomato puree. But 'passeggiata' means 'a walk/stroll'. So 'passata' sounds like the tomato is going for a stroll. Wordplay at its finest!" },
  { text: "Cosa dice un muro a un altro muro?\nCi vediamo all'angolo.", dan: "What does a wall say to another wall? 'See you at the corner'. Simple, classic, and perfectly translatable!" },
  { text: "Perché il libro di matematica è sempre triste?\nPerché ha troppi problemi.", dan: "Why is the math book always sad? Because it has too many problems. 'Problemi' works for both math equations and emotional issues, just like in English!" },
  { text: "Qual è la città preferita dai ragni?\nMosca.", dan: "What is a spider's favorite city? Moscow! In Italian, the capital of Russia is called 'Mosca', which is the exact same word we use for a 'fly' 🪰." },
  { text: "Cosa fa un cane in chiesa?\nAscolta la Messa... in piega!", dan: "This is a pun on 'Messa' (church Mass) and 'Messa in piega' (a blowout/hair styling at the salon). So the dog is getting its hair done at church!" },
  { text: "Un limone dice a un altro limone:\nLimoniamo?", dan: "'Limonare' is Italian slang for 'to make out / to French kiss'. So one lemon says to the other: 'Shall we make out?'" },
  { text: "Qual è il colmo per un medico?\nEssere molto paziente.", dan: "In Italy, we love 'Qual è il colmo?' (What is the height of irony?) jokes. For a doctor, the height of irony is being very 'paziente' (which means both 'patient' as a virtue, and 'a patient' in a hospital)." },
  { text: "Cosa fanno due caramelle al campo da tennis?\nSi scartano.", dan: "What do two candies do on a tennis court? They dodge each other! 'Scartare' means to dodge/dribble in sports, but it also means 'to unwrap' a candy." },
  { text: "Come si chiama il cane di Dracula?\nCanino.", dan: "What is Dracula's dog called? 'Canino'. It's a pun because 'cane' (dog) + 'ino' (little) means little dog, but 'canino' is also the canine tooth (fang)!" },
  { text: "Cosa dice il mare alla spiaggia?\nNiente, saluta con l'onda.", dan: "What does the sea say to the beach? Nothing, it waves! 'Saluta con l'onda' literally means 'greets with the wave'." }
];

const commediaMediumDB = [
  { text: "Qual è il colmo per un idraulico?\nFare un buco nell'acqua.", dan: "An 'idraulico' is a plumber. 'Fare un buco nell'acqua' (to make a hole in water) is a famous idiom meaning 'to fail completely'. A plumber failing by making a hole in water... peak Italian dad joke!" },
  { text: "Due casseforti si incontrano per strada:\nChe combinazione!", dan: "Two safes meet on the street: 'What a combination!'. 'Combinazione' means a safe's code, but it's also the Italian word for 'Coincidence'!" },
  { text: "Cosa ci fa una TV in mare?\nVa in onda.", dan: "What is a TV doing in the sea? It's 'going on the wave'. 'Andare in onda' is the Italian expression for 'going on air / broadcasting'." },
  { text: "Perché il pomodoro non dorme?\nPerché l'insalata russa.", dan: "Why doesn't the tomato sleep? Because the Russian salad! Wait, what? In Italian, 'Russa' means both 'Russian' and 'He/She snores' (from the verb russare). The salad is snoring!" },
  { text: "Qual è il colmo per un sarto?\nPerdere il filo del discorso.", dan: "A 'sarto' is a tailor. The idiom 'perdere il filo del discorso' means to lose one's train of thought. But literally, it means 'to lose the thread of the speech'!" },
  { text: "Cosa fanno tre maiali sul divano?\nI porci comodi.", dan: "The idiom 'Fare i propri porci comodi' means to do exactly as you please, lazily and selfishly. Literally: 'To do your own comfortable pigs'. Three pigs on a couch are doing just that." },
  { text: "Qual è il colmo per un calvo?\nAvere un diavolo per capello.", dan: "A 'calvo' is a bald man. The idiom 'Avere un diavolo per capello' (To have a devil for each hair) means to be incredibly furious. A bald man can't possibly have a devil for each hair!" },
  { text: "Un daino dice a un altro daino:\nFacciamo a nascondaino?", dan: "A 'daino' is a deer. The game Hide and Seek is called 'Nascondino'. Since they are deer, they play 'Nascon-daino'!" },
  { text: "Qual è il colmo per un elettricista?\nPrendere la scossa... e non potersela tenere!", dan: "The height of irony for an electrician? Taking a shock (prendere la scossa)... and not being able to keep it!" },
  { text: "Cosa dice un semaforo a un altro semaforo?\nNon guardarmi che sto diventando rosso!", dan: "What does one traffic light say to the other? 'Don't look at me, I'm turning red!'. 'Diventare rosso' means both the traffic light changing and a person blushing." }
];

const commediaHardDB = [
  { text: "- Dottore, nessuno mi ignora!\n- Il prossimo!", dan: "The patient says 'Doctor, nobody ignores me!'. The doctor immediately yells 'Next!' (Il prossimo), thereby completely ignoring him. Classic dry Italian humor." },
  { text: "Pierino chiede alla mamma: 'Hai visto il mio orologio?'\n'Sì, è andato avanti.'\n'E dove è andato?'", dan: "Pierino is the classic mischievous kid in Italian jokes. 'Andare avanti' means to walk forward, but for a clock, it means 'to run fast'. Pierino takes it literally!" },
  { text: "La maestra: 'Dimmi il tempo presente del verbo camminare.'\n'Io cammino, tu cammini...'\n'Più in fretta!'\n'Io corro, tu corri!'", dan: "The teacher asks for the present tense of 'to walk' (camminare). Then she says 'Faster!' (meaning conjugate faster). Pierino instead conjugates the verb 'to run' (correre)!" },
  { text: "Una signora: 'Vorrei provare quel vestito in vetrina.'\nCommesso: 'Signora, non può provarlo in camerino come tutte le altre?'", dan: "The lady says 'I would like to try on that dress in the shop window (in vetrina)'. The clerk takes it literally: 'Can't you try it on in the dressing room like everyone else?'" },
  { text: "Vigile: 'Le devo fare la multa, lei ha superato i 130!'\nGuidatore: 'Ma se ho solo 40 anni!'", dan: "A traffic cop pulls a car over: 'I have to fine you, you passed 130!'. The driver replies: 'But I'm only 40 years old!'. 130 km/h is the max speed limit on Italian highways." },
  { text: "Qual è la differenza tra uno specchio e un chiacchierone?\nLo specchio riflette senza parlare, il chiacchierone parla senza riflettere.", dan: "Beautiful language joke. 'Riflettere' means both 'to reflect light' (mirror) and 'to think/reflect' (human). A chatterbox speaks without reflecting, a mirror reflects without speaking." },
  { text: "Pronto, parlo col manicomio?\nNo, qui siamo tutti sani di mente!\nScusi, ho sbagliato numero.", dan: "'Hello, am I speaking with the asylum?' 'No, we are all perfectly sane here!' 'Sorry, wrong number.' It's a joke on the absurdity of denying craziness." },
  { text: "Qual è il colmo per un musicista?\nPrendere un sacco di note... a scuola.", dan: "A musician's paradox? Getting a lot of 'note'. In music, 'note' are musical notes. In Italian schools, a 'nota' is a written disciplinary warning for bad behavior!" },
  { text: "Al ristorante: 'Cameriere, c'è una mosca nella mia minestra!'\n'Non si preoccupi signore, non berrà molto.'", dan: "Customer: 'Waiter, there is a fly in my soup!'. Waiter: 'Don't worry sir, it won't drink too much.' The classic deflection of a complaint." },
  { text: "Sai perché l'arancia non va mai a fare la spesa?\nPerché manda il mandarino.", dan: "Why doesn't the orange go grocery shopping? Because it sends the mandarin. 'Manda' comes from the verb 'Mandare' (to send). Manda-rino!" }
];

const commediaNativeDB = [
  { text: "Un signore entra in un caffè.\nSplash.", dan: "The shortest, most famous anti-joke in Italy. 'Entrare in un caffè' means to walk into a coffee shop. But 'un caffè' also means a literal cup of espresso. So he steps into the coffee... Splash." },
  { text: "Qual è il colmo per una zanzara?\nEssere donatrice di sangue.", dan: "The height of irony for a 'zanzara' (mosquito)? Being a blood donor! (Donatrice di sangue)." },
  { text: "Cosa dice un pettine a un calvo?\nNon mi fai un baffo!", dan: "What does a comb say to a bald man? 'Non mi fai un baffo!' (You don't make me a mustache). It's an idiom meaning 'You don't affect me / I don't care at all'." },
  { text: "Cosa fanno due api vicine?\nL'Ape-ritivo.", dan: "What do two bees (api) do when they get together? They have an Ape-ritivo! Happy hour (Aperitivo) is an institution in Italy." },
  { text: "Come si chiama il più famoso ladro giapponese?\nChito Fregato.", dan: "Italians love making fake foreign names that sound like Italian phrases. 'Chito Fregato' sounds vaguely Japanese, but it means 'Chi t'ha fregato?' (Who robbed you?)." },
  { text: "Come si chiama la più nota ballerina russa?\nCiolanka Sbilenca.", dan: "Another fake name! 'Ciolanka Sbilenca' sounds Russian, but in Italian it sounds like 'C'ho l'anca sbilenca' (I have a crooked hip) - terrible for a ballerina!" },
  { text: "Una gallina dice a un'altra gallina:\nHai fatto l'uovo?\nNo, ci sto covando sopra.", dan: "One hen says to another: 'Did you lay the egg?' 'No, I'm brooding over it'. 'Covare' means to incubate an egg, but 'ci sto covando sopra' also means 'I'm plotting/thinking about it'." },
  { text: "Colmo per un astronauta?\nEssere un tipo terra terra.", dan: "The height of irony for an astronaut? Being a 'terra terra' guy. 'Terra terra' means down-to-earth, simple, or basic." },
  { text: "Perché un computer va dal medico?\nPerché ha un virus.", dan: "Why does the computer go to the doctor? Because it has a virus. A global joke, but works perfectly in Italian too." },
  { text: "Che differenza c'è tra un avvocato e un gallo?\nIl gallo si alza quando spunta il sole, l'avvocato quando spunta un problema.", dan: "What's the difference between a lawyer and a rooster? The rooster gets up when the sun rises, the lawyer gets up when a problem rises. (Spuntare = to emerge/rise)." }
];

const appData = {
    "pillole": [
        {"id": "p1", "difficulty": "easy", "title": "In bocca al lupo!", "italian": "In bocca al lupo", "pronunciation": "een BOK-kah ahl LOO-poh", "literal": "Into the wolf's mouth", "english": "Good luck! (Break a leg)", "danielNotes": "Never say 'Grazie' to this! You must reply: 'Crepi il lupo!' (May the wolf die!)"},
        {"id": "p2", "difficulty": "easy", "title": "Mamma mia!", "italian": "Mamma mia!", "pronunciation": "MAHM-mah MEE-ah", "literal": "My mother!", "english": "Oh my goodness! / Wow!", "danielNotes": "We use this for everything: surprise, frustration, joy. It's the ultimate Italian reaction."},
        {"id": "p3", "difficulty": "medium", "title": "Che figata!", "italian": "Che figata!", "pronunciation": "keh fee-GAH-tah", "literal": "What a fig-ness!", "english": "How cool! / That's awesome!", "danielNotes": "Very informal but extremely common slang among young people."},
        {"id": "p4", "difficulty": "high", "title": "Piove sul bagnato", "italian": "Piove sul bagnato", "pronunciation": "PYOH-veh sool bah-NYAH-toh", "literal": "It rains on the wet", "english": "When it rains, it pours / The rich get richer", "danielNotes": "Used when good things happen to lucky people, or bad things keep happening to unlucky people."},
        {"id": "p5", "difficulty": "mamma_mia", "title": "Avere la botte piena e la moglie ubriaca", "italian": "Avere la botte piena e la moglie ubriaca", "pronunciation": "ah-VEH-reh lah BOHT-teh PYEH-nah e lah MO-lyeh oo-bree-AH-kah", "literal": "To have the barrel full and the wife drunk", "english": "You can't have your cake and eat it too", "danielNotes": "This is a classic Italian proverb. You have to make a choice!"}
    ],
  quiz: [
    ...quizEasyDB.map((item, i) => ({ id: 'q_easy_' + i, difficulty: 'easy', question: item.q, options: item.o, correctAnswer: item.a, rule: item.rule || '', example: item.ex || '', danielNotes: item.dan })),
    ...quizMediumDB.map((item, i) => ({ id: 'q_medium_' + i, difficulty: 'medium', question: item.q, options: item.o, correctAnswer: item.a, rule: item.rule || '', example: item.ex || '', danielNotes: item.dan })),
    ...quizHardDB.map((item, i) => ({ id: 'q_high_' + i, difficulty: 'high', question: item.q, options: item.o, correctAnswer: item.a, rule: item.rule || '', example: item.ex || '', danielNotes: item.dan })),
    ...quizNativeDB.map((item, i) => ({ id: 'q_mamma_mia_' + i, difficulty: 'mamma_mia', question: item.q, options: item.o, correctAnswer: item.a, rule: item.rule || '', example: item.ex || '', danielNotes: item.dan })),
  ],
  traduzioni: [
    ...traduzioniEasyDB.map((item, i) => ({ id: 't_easy_' + i, difficulty: 'easy', english: item.q, answers: item.a, italian: item.a[0], danielNotes: item.dan, hints: [] })),
    ...traduzioniMediumDB.map((item, i) => ({ id: 't_medium_' + i, difficulty: 'medium', english: item.q, answers: item.a, italian: item.a[0], danielNotes: item.dan, hints: [] })),
    ...traduzioniHardDB.map((item, i) => ({ id: 't_high_' + i, difficulty: 'high', english: item.q, answers: item.a, italian: item.a[0], danielNotes: item.dan, hints: [] })),
    ...traduzioniNativeDB.map((item, i) => ({ id: 't_mamma_mia_' + i, difficulty: 'mamma_mia', english: item.q, answers: item.a, italian: item.a[0], danielNotes: item.dan, hints: [] })),
  ],
  multisenso: [
    ...multisensoEasyDB.map((item, i) => ({ id: 'm_easy_' + i, difficulty: 'easy', sentence: item.q, options: item.o, correctAnswer: item.a, danielNotes: item.dan })),
    ...multisensoMediumDB.map((item, i) => ({ id: 'm_medium_' + i, difficulty: 'medium', sentence: item.q, options: item.o, correctAnswer: item.a, danielNotes: item.dan })),
    ...multisensoHardDB.map((item, i) => ({ id: 'm_high_' + i, difficulty: 'high', sentence: item.q, options: item.o, correctAnswer: item.a, danielNotes: item.dan })),
    ...multisensoNativeDB.map((item, i) => ({ id: 'm_mamma_mia_' + i, difficulty: 'mamma_mia', sentence: item.q, options: item.o, correctAnswer: item.a, danielNotes: item.dan })),
  ],
  commedia: [
    ...commediaEasyDB.map((item, i) => ({ id: 'c_easy_' + i, difficulty: 'easy', joke: item.text, danielNotes: item.dan })),
    ...commediaMediumDB.map((item, i) => ({ id: 'c_medium_' + i, difficulty: 'medium', joke: item.text, danielNotes: item.dan })),
    ...commediaHardDB.map((item, i) => ({ id: 'c_high_' + i, difficulty: 'high', joke: item.text, danielNotes: item.dan })),
    ...commediaNativeDB.map((item, i) => ({ id: 'c_mamma_mia_' + i, difficulty: 'mamma_mia', joke: item.text, danielNotes: item.dan })),
  ]
};
